project:
  type: website
  output-dir: docs

website:
  title: "sid_site"
  navbar:
    left:
      - href: index.qmd
        text: About
      - resume.qmd
      - href: blog.qmd
        text: Projects

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



